<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * AlimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheAliment($data)
    {


        $queryBuilder = $this->createQueryBuilder('a');

        /*$queryBuilder->leftJoin('a.marque', 'marque')
            ->addSelect('marque')
            ->leftJoin('a.modele', 'modele')
            ->addSelect('modele');*/

        if(isset($data['code']) && !empty($data['code'])){
            $queryBuilder->andWhere('a.code like :code')
                ->setParameter('code', '%'.$data['code'].'%');
        }



        /*$query = $queryBuilder->getQuery();
        $results = $query->getResult();*/

        return $queryBuilder;
    }
}
