<?php

namespace Pfe\SuiviVacheBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * DistrubtionAlimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrubtionAlimentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDistributionVacheJour($id_lot, $date)
    {
        $queryBuilder = $this->createQueryBuilder('d')
            ->leftJoin('d.vache', 'vache')
            ->addSelect('vache');

        $queryBuilder->andWhere('vache.lot = :lot')
            ->setParameter('lot', $id_lot)
            ->andWhere('d.dateDistribution = :date')
            ->setParameter('date', $date);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
