<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * DoseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoseRepository extends \Doctrine\ORM\EntityRepository
{
}
