<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * EtableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtableRepository extends \Doctrine\ORM\EntityRepository
{
}
