<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * FourniseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FourniseurRepository extends \Doctrine\ORM\EntityRepository
{
}
