<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * LignesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignesRepository extends \Doctrine\ORM\EntityRepository
{
}
