<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * LotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheLot($data)
    {


        $queryBuilder = $this->createQueryBuilder('a');

        /*$queryBuilder->leftJoin('a.marque', 'marque')
            ->addSelect('marque')
            ->leftJoin('a.modele', 'modele')
            ->addSelect('modele');*/

        if(isset($data['numLot']) && !empty($data['numLot'])){
            $queryBuilder->andWhere('a.numLot like :numLot')
                ->setParameter('numLot', '%'.$data['numLot'].'%');
        }



        /*$query = $queryBuilder->getQuery();
        $results = $query->getResult();*/

        return $queryBuilder;
    }
}
