<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * ProductionlaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionlaitRepository extends \Doctrine\ORM\EntityRepository
{
}
