<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * RationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAliment($id_trancheAge, $id_race,$id_typeVache) {

        $queryBuilder = $this->createQueryBuilder('r');
        $queryBuilder->andWhere('r.trancheAge = :trancheAge')
            ->setParameter('trancheAge', $id_trancheAge)
            ->andWhere('r.race = :race')
            ->setParameter('race', $id_race)
            ->andWhere('r.typeVache = :typeVache')
            ->setParameter('typeVache', $id_typeVache);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
