<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * ReceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
