<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * SuiviPoidsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviPoidsRepository extends \Doctrine\ORM\EntityRepository
{
}
