<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * TypeVacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVacheRepository extends \Doctrine\ORM\EntityRepository
{
}
