<?php

namespace Pfe\SuiviVacheBundle\Repository;

/**
 * VacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacheRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheVache($data)
    {


        $queryBuilder = $this->createQueryBuilder('a');

        /*$queryBuilder->leftJoin('a.marque', 'marque')
            ->addSelect('marque')
            ->leftJoin('a.modele', 'modele')
            ->addSelect('modele');*/

        if(isset($data['numero']) && !empty($data['numero'])){
            $queryBuilder->andWhere('a.numero like :numero')
                ->setParameter('numero', '%'.$data['numero'].'%');
        }
        if(isset($data['ageMin']) && !empty($data['ageMin'])){
            $queryBuilder->andWhere('a.age >= :ageMin')
                ->setParameter('ageMin', $data['ageMin']);
        }
        if(isset($data['ageMax']) && !empty($data['ageMax'])){
            $queryBuilder->andWhere('a.age <= :ageMax')
                ->setParameter('ageMax', $data['ageMax']);
        }


        /*$query = $queryBuilder->getQuery();
        $results = $query->getResult();*/

        return $queryBuilder;
    }

}